## Task
- Complete **isHappy** function following the description below

### Happy Number
Write an algorithm to determine if a number **n** is happy.

A **happy number** is a number defined by the following process:

* Starting with any positive integer, replace the number by the sum of the squares of its digits.
* Repeat the process until the number equals 1 (where it will stay), or it **loops endlessly in a cycle** which does not include 1.
* Those numbers for which this process **ends in 1** are happy.

Return **true** if n is a happy number, and **false** if not.

Constraints:
1 <= n <= $2^{31}$ - 1

In [11]:
import math

def isHappy(n):

  n_temp = n

  while True:
    temp = str(n_temp)
    num_list = list(temp)

    new_n = 0

    for num in num_list:
      new_n += int(num)*int(num)

    n_temp = new_n

    if new_n == 1:
      return True
    if new_n == n or new_n >= math.pow(2, 31):
      return False

print(isHappy(19))

True

**Testcase 1.**

**Input**: n = 19

**Output**: True

**Explanation**:

$1^2 + 9^2 = 82$

$8^2 + 2^2 = 68$

$6^2 + 2^2 = 100$

$1^2 + 0^2 + 0^2 = 1$

**Testcase 2.**

**Input**: n = 2

**Output**: False